version: '3.8'

services:
  bot:
    build: .
    container_name: ceiling-calc-bot
    env_file: .env
    volumes:
      - ./bot.db:/app/bot.db
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 